# Automatically generated by configure - do not modify
SRC_PATH=/tptogiar/virtual-alpha/qemu/qemu-5.1.0/roms/seabios
AS=as
CCAS=ccache gcc
CC=ccache gcc
BCC=bcc
CPP=ccache gcc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
